version: "3.5"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Uotz123
    volumes:
      - mongo-data:/data/db
      - type: bind
        source: ./bad_comments/bad_comments.csv
        target: /bad_comments/bad_comments.csv
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    name: naive-bayes
    driver: bridge

volumes:
  mongo-data:
    driver: local
  bad_comments:
    driver: local
